os:
  - linux
  - osx

language: go

go:
    - 1.9.2

install: true

script:
  - make deps
  - go test ./...
  - go vet ./...

cache:
    directories:
        - $GOPATH/src/gx

notifications:
  email: false
